### ISSUE TITLE
[BUG] Architecture images that are too large cannot be imported

### ISSUE THREAD

**Issue by cogwirrel** [awslabs/threat-composer#100]
### Describe the bug

Architecture images from threat models generated by PDK's [cdk graph plugin](https://aws.github.io/aws-pdk/developer_guides/cdk-graph-plugin-threat-composer/index.html) are often too large to import and fail.

### Expected Behavior

Images to import successfully

### Current Behavior

![Screenshot 2024-03-14 at 9 23 51 am](https://github.com/awslabs/threat-composer/assets/1848603/e57594c4-3ff2-48a4-b9a7-02645eda6605)

### Reproduction Steps

* Follow the PDK [getting started guide](https://aws.github.io/aws-pdk/getting_started/your_first_aws_pdk_project.html) to create a project (with an api, website and infrastructure).
* Import the generated threat model (`packages/infra/cdk.out/cdkgraph/threat-composer.tc.json`) into threat composer

### Possible Solution

Either increase the size limit, or add support for svg images which will generally be smaller.

**Comment by jessieweiyi** [comment]
Hi @cogwirrel, thanks for reporting the bug. 

Currently, the base 64 image field is limited to 1,000,000 characters. Since we are using local storage, we are cautious about the data size. 

We do support usage of svg. However, there is a bug when validating the image field for image/svg+xml format. We will release a bug fix soon.

**Comment by cogwirrel** [comment]
Awesome, thank you! 😄
