### ISSUE TITLE
[BUG] Threats/mitigations from reference packs cause re-import of saved workspace to fail

### ISSUE THREAD

**Issue by idpdevops** [awslabs/threat-composer#143]
### Describe the bug

When I add mitigations from the reference packs to a threat model and then save the model, then I can't re-import the file - it throws an error. It happens even if I delete the workspace, re-create it and then import the file.

![image (4)](https://github.com/user-attachments/assets/66277a61-a960-41db-8037-1b1c0f690ddd)

### Expected Behavior

I would expect the saved file to be loaded without errors.

### Current Behavior

An error occurs, see attached screenshot
![image (4)](https://github.com/user-attachments/assets/a6705bca-df7c-438f-893c-8c66ca82ce81)

### Reproduction Steps

1. Create a workspace
2. Add a threat and a mitigation from one of the threat/mitigation packs (even a single threat causes the problem)
3. Export the workspace
4. Delete the workspace
5. Create a workspace
6. Import the previously exported file
7. Error occurs

### Possible Solution

n/a

**Comment by idpdevops** [comment]
Sorry, forgot to add this for reference

[ThreatComposer_Workspace_test.tc (1).json](https://github.com/user-attachments/files/17201577/ThreatComposer_Workspace_test.tc.1.json)

**Comment by jessieweiyi** [comment]
Hi @idpdevops, 

We have released a [fix](https://github.com/awslabs/threat-composer/commit/180fa1ee1cb6c0e9281949b668d7987dc8f4063b) to address this issue early last week. Your browser might not run the latest deployment due to local cache. You can run a hard refresh (WITHOUT deleing local history/data) in your browser to load the latest version of threat composer. For example, if you are using Mac and Chrome, you can hold down ⌘ Cmd and ⇧ Shift key and then press R.

For exported tc json file, if validation issues are still present during re-import, you can open the file in text editor, remove all the "comments" (all lower case) field and value under mitigations props and reimport again.

**Comment by idpdevops** [comment]
Thanks, that must have been shortly after I installed it. Updating to the latest version now.

**Comment by jessieweiyi** [comment]
Hi @idpdevops  Closing this issue based on the comment above. Feel free to reopen if the problem still exists. Thank you.
