### ISSUE TITLE
[BUG] inconsistent string data output rendering in threat model view

### ISSUE THREAD

**Issue by brodieve** [awslabs/threat-composer#17]
### Describe the bug

In the threats component, impacted assets and goals, as an example, accept and display strings that include html tags.

In the threat model view, all threats, impacted assets, etc. unnecessarily have this data removed, leading to inconsistency.

The reason for the issue is that we're using `sanitizeHtml` in the latter.

### Expected Behavior

All views including the threat model view should use a consistent approach to encoding and displaying untrusted string output.

### Current Behavior

We strip tags in ThreatModelView report component, a change that was bundled in with this MarkdownViewer task:

https://github.com/awslabs/threat-composer/commit/3e5be78ad1d1fa7d82fabd8069bad9bfa97b3a5e#diff-1561f83418f689c14ced35e795c825294404553d8587439b85d152c6f365567bR48

### Reproduction Steps

1. Start creating a new threat.
2. Populate some impacted assets and goals that are, or include, html tags.
3. Save threat. 
4. Switch to the threat model view.

### Possible Solution

Remove html sanitization util, ensure consistent output encoding.

Not sure what `sanitizeHtml` is trying to accomplish or where it's supposed to be used, but the utility and its currently empty allowedTags array is worthy of reconsideration to me.

**Comment by jessieweiyi** [comment]
Hi @brodieve, Thanks for reporting the bug. 

Threat Composer does not support html tags text content at the moment. However, it is on our roadmap. We remove the html from MarkdownViewer data source to prevent raw html from being rendered.

**Comment by dboyd13** [comment]
@brodieve Thanks for your detailed bug report. We do agree that strings rendered should be rendered consistently across the app.

Threat Composer is designed to not allow user input to include HTML tags. The primary enforcement of this is by running user input through `sanitizeHtml` on Threat model render, and on import. In addition, there is a UX aspect which uses RegEx detection of tag input to trigger a UI warning to let the user know HTML tags are not supported. User input via UI is dynamically checked (per keypress) and in some cases dynamically rendered (e.g. threat statement), meaning that if they attempt to type in a tag (e.g. `<IMG>`), it will allow them to get as far as `<IMG` before the regex fires, and if they remove the `>` (leaving `<IMG`) and it will not prevent them from saving, because the RegEx would not have fired (by design). What you have found is that the later is not true in the case of the 'impacted goal' and 'impacted assets' user input fields. Additionally, our investigations highlight that the way a given string that includes partial HTML tag differs in rendering between the input page (e.g. Threat editor or Threat list) versus the rendered Threat Model this is because by default `sanitizeHtml` would discard an open and incomplete tag (e.g. `<IMG`) and any text after it.

Investigation is underway for fixes.
