### ISSUE TITLE
[BUG] Images are missing

### ISSUE THREAD

**Issue by holttim** [awslabs/threat-composer#62]
### Describe the bug

When I import a saved json workspace, the architecture and dataflow diagrams are erroring out:
dataflow,image: Invalid image format
I can edit the json and delete the content in "dataflow": {
    "image": "data:image/png
then I can import the workspace.  
I suspect there may be a file size limitation for uploaded images.

### Expected Behavior

I expected the imported images to be saved and imported.

### Current Behavior

Error when importing: dataflow,image: Invalid image format

### Reproduction Steps

1.  Create a new workspace
2. under the dataflow diagram upload from your computer a PNG file that is over 500K in size.
3. save the image to the workspace.
4. Export the workspace to your computer.
5. Open a new browser window and go to the threat composer.
6. Import the workspace you just created.
7. It will error out and say: Error when importing: dataflow,image: Invalid image format

### Possible Solution

I suspect that any image over 500k is truncated and corrupted when converted to json.

**Comment by jessieweiyi** [comment]
Hi @holttim, Thanks for reporting the bug. We will have a look later this week.

**Comment by jessieweiyi** [comment]
Hi @holttim, 

Thanks for reporting the bug. 

Currently, we have set the image base64 size limit to 500000 characters to encourage users to upload smaller size images because of very limited local storage space. However, when users upload an image file with more that 500K, we do not show the error message until users export and reimport the json file because the validation failed.

A PR has been raised to increase the file size limit to 1MB to cater for your use case and also if the file size exceeds the size limit when the file is uploaded, error message will be displayed.
